In [1]:

import pandas as pd

print("Welcome to NWSL Performance Analytics!")
print("Pandas version:", pd.__version__)

Welcome to NWSL Performance Analytics!
Pandas version: 2.2.3

In [3]:
player_url = "https://raw.githubusercontent.com/leaaa2000/NWSL-Performance-Analytics/main/data/raw/adv_player_stats.csv"

team_url = "https://raw.githubusercontent.com/leaaa2000/NWSL-Performance-Analytics/main/data/raw/adv_team_stats.csv"

players = pd.read_csv(player_url)
teams = pd.read_csv(team_url)

print("Player dataset shape:", players.shape)
print("Team dataset shape:", teams.shape)

Player dataset shape: (15696, 272)
Team dataset shape: (890, 240)

/tmp/ipykernel_442/2221026930.py:5: DtypeWarning: Columns (237,263) have mixed types. Specify dtype option on import or set low_memory=False.
  players = pd.read_csv(player_url)

In [18]:
# Take a look at both datasets
print("PLAYER DATASET:")
display(players.head())

print("TEAM DATASET:")
display(teams.head())

PLAYER DATASET:

,game_id,status,team_id,player_id,first_name,last_name,match_name,shirt_number,position,position_side,...,rc,assist_post,penalty_save,att_pen_target,assist_own_goal,back_pass,att_lg_right,formation_place_1,att_corner,season
0,portland-thorns-vs-houston-dash-2016-09-07,home,POR,9ifjrfggioh9cmphk85gykzx1,Michelle,Betos,M. Betos,18,Goalkeeper,Centre,...,0,0.0,0,0,NaN,NaN,NaN,NaN,NaN,2016
1,portland-thorns-vs-houston-dash-2016-09-07,home,POR,bnnc9csv7qrc2xgx7yzgxlcr9,Meghan,Klingenberg,M. Klingenberg,25,Defender,Left,...,0,0.0,0,0,NaN,NaN,NaN,NaN,NaN,2016
2,portland-thorns-vs-houston-dash-2016-09-07,home,POR,5zwpytehpeosi3sfckvkuy3md,Emily,Menges,E. Menges,4,Defender,Left/Centre,...,0,0.0,0,0,NaN,NaN,NaN,NaN,NaN,2016
3,portland-thorns-vs-houston-dash-2016-09-07,home,POR,3aj7p478dcuat6tz8096sq8dl,Emily,Sonnett,E. Sonnett,16,Defender,Centre/Right,...,0,0.0,0,0,NaN,NaN,NaN,NaN,NaN,2016
4,portland-thorns-vs-houston-dash-2016-09-07,home,POR,2usg5n5edeznax3nybdta11x,Katherine,Reynolds,K. Reynolds,2,Defender,Right,...,0,0.0,0,0,NaN,NaN,NaN,NaN,NaN,2016

TEAM DATASET:

,game_id,status,team,total_through_ball,duel_lost,blocked_scoring_att,leftside_pass,poss_won_att_3_rd,dispossessed,accurate_keeper_sweeper,...,attempts_obox,attempts_ibox,att_pen_miss,goal_fastbreak,att_obp_goal,penalty_save,att_pen_target,att_lg_right,att_corner,season
0,portland-thorns-vs-houston-dash-2016-09-07,home,POR,1,32,5,112,13,16,1,...,0,0,0.0,0,0,0,0,NaN,NaN,2016
1,portland-thorns-vs-houston-dash-2016-09-07,away,HOU,1,35,2,78,3,17,1,...,0,0,0.0,0,0,0,0,NaN,NaN,2016
2,western-new-york-flash-vs-kansas-city-2016-07-23,home,WNY,0,56,1,60,11,13,2,...,0,0,0.0,0,0,0,0,NaN,NaN,2016
3,western-new-york-flash-vs-kansas-city-2016-07-23,away,KC,3,49,2,40,2,9,0,...,0,0,0.0,0,0,0,0,NaN,NaN,2016
4,western-new-york-flash-vs-houston-dash-2016-08-27,home,WNY,1,51,1,69,5,4,1,...,0,0,0.0,0,0,0,0,NaN,NaN,2016

In [19]:

# Get the season from the game ID
players["season"] = players["game_id"].str.extract(r"(\d{4})-\d{2}-\d{2}$")
teams["season"] = teams["game_id"].str.extract(r"(\d{4})-\d{2}-\d{2}$")

# See how many records are in each season
print("PLAYER DATA BY SEASON:")
print(players["season"].value_counts(dropna=False).sort_index())

print("\nTEAM DATA BY SEASON:")
print(teams["season"].value_counts(dropna=False).sort_index())

PLAYER DATA BY SEASON:
season
2016    3582
2017    4203
2018    3935
2019    3976
Name: count, dtype: int64

TEAM DATA BY SEASON:
season
2016    206
2017    240
2018    222
2019    222
Name: count, dtype: int64

In [20]:
# Check which columns have missing data
player_missing = players.isnull().sum()
team_missing = teams.isnull().sum()

print("PLAYER DATA - TOP 15 COLUMNS WITH MISSING VALUES:")
print(player_missing.sort_values(ascending=False).head(15))

print("\nTEAM DATA - TOP 15 COLUMNS WITH MISSING VALUES:")
print(team_missing.sort_values(ascending=False).head(15))

PLAYER DATA - TOP 15 COLUMNS WITH MISSING VALUES:
formation_place_1      11720
att_corner             11720
att_lg_right            7785
back_pass               7517
assist_post             4203
second_yellow           3935
foul_throw_in           3935
y_2_c                   3935
att_pen_miss            3935
assist_own_goal         3582
first_name               376
saved_ibox                 0
stand_catch                0
good_high_claim            0
goals_conceded_ibox        0
dtype: int64

TEAM DATA - TOP 15 COLUMNS WITH MISSING VALUES:
att_corner                 668
att_lg_right               446
second_yellow              222
foul_throw_in              222
att_pen_miss               222
status                       0
team                         0
total_through_ball           0
dispossessed                 0
accurate_keeper_sweeper      0
accurate_cross               0
att_rf_total                 0
duel_lost                    0
blocked_scoring_att          0
leftside_pass                0
dtype: int64

In [21]:
# Keep the player stats I want to analyze
player_columns = [
    "game_id",
    "season",
    "team_id",
    "player_id",
    "first_name",
    "last_name",
    "position",
    "goals",
    "goal_assist",
    "total_shots",
    "total_pass",
    "accurate_pass"
]

players_clean = players[player_columns].copy()

# Check the smaller dataset
print("SELECTED PLAYER DATA:")
print("Shape:", players_clean.shape)

print("\nMISSING VALUES:")
print(players_clean.isnull().sum())

display(players_clean.head())

SELECTED PLAYER DATA:
Shape: (15696, 12)

MISSING VALUES:
game_id            0
season             0
team_id            0
player_id          0
first_name       376
last_name          0
position           0
goals              0
goal_assist        0
total_shots        0
total_pass         0
accurate_pass      0
dtype: int64

,game_id,season,team_id,player_id,first_name,last_name,position,goals,goal_assist,total_shots,total_pass,accurate_pass
0,portland-thorns-vs-houston-dash-2016-09-07,2016,POR,9ifjrfggioh9cmphk85gykzx1,Michelle,Betos,Goalkeeper,0,0,0,41,35
1,portland-thorns-vs-houston-dash-2016-09-07,2016,POR,bnnc9csv7qrc2xgx7yzgxlcr9,Meghan,Klingenberg,Defender,0,0,1,42,36
2,portland-thorns-vs-houston-dash-2016-09-07,2016,POR,5zwpytehpeosi3sfckvkuy3md,Emily,Menges,Defender,0,0,0,64,58
3,portland-thorns-vs-houston-dash-2016-09-07,2016,POR,3aj7p478dcuat6tz8096sq8dl,Emily,Sonnett,Defender,0,0,1,67,57
4,portland-thorns-vs-houston-dash-2016-09-07,2016,POR,2usg5n5edeznax3nybdta11x,Katherine,Reynolds,Defender,0,0,0,32,24

In [22]:
# See which players are missing first names
missing_names = players_clean[
    players_clean["first_name"].isna()
]

print("Records with missing first names:", len(missing_names))

print("\nMissing first names by season:")
print(missing_names["season"].value_counts().sort_index())

print("\nExamples of missing first names:")
display(
    missing_names[
        ["season", "team_id", "player_id", "first_name", "last_name"]
    ].head(15)
)

Records with missing first names: 376

Missing first names by season:
season
2016     46
2017    137
2018    108
2019     85
Name: count, dtype: int64

Examples of missing first names:

     season team_id                  player_id first_name    last_name
22     2016     HOU  5fkw18yxmk3wccr46kjtoz5xx        NaN      Poliana
24     2016     HOU  479w7uwn18x7ciwkoqukstmtx        NaN  Andressinha
89     2016     HOU  5fkw18yxmk3wccr46kjtoz5xx        NaN      Poliana
93     2016     HOU  479w7uwn18x7ciwkoqukstmtx        NaN  Andressinha
572    2016     ORL  3iangrthyltpl31m4v1qkgn2t        NaN       Monica
646    2016     HOU  5fkw18yxmk3wccr46kjtoz5xx        NaN      Poliana
649    2016     HOU  479w7uwn18x7ciwkoqukstmtx        NaN  Andressinha
684    2016     ORL  3iangrthyltpl31m4v1qkgn2t        NaN       Monica
701    2016     HOU  5fkw18yxmk3wccr46kjtoz5xx        NaN      Poliana
702    2016     HOU  479w7uwn18x7ciwkoqukstmtx        NaN  Andressinha
821    2016     HOU  5fkw18yxmk3wccr46kjtoz5xx        NaN      Poliana
824    2016     HOU  479w7uwn18x7ciwkoqukstmtx        NaN  Andressinha
960    2016     ORL  3iangrthyltpl31m4v1qkgn2t        NaN       Monica
1030   2016     ORL  3iangrthyltpl31m4v1qkgn2t        NaN       Monica
1261   2016     HOU  5fkw18yxmk3wccr46kjtoz5xx        NaN      Poliana

In [9]:

# Create a display name without losing player records

players_clean["player_name"] = (
    players_clean["first_name"]
    .fillna("")
    .str.strip()
    + " "
    + players_clean["last_name"].fillna("").str.strip()
).str.strip()

# Check the results
print("Missing player display names:")
print(players_clean["player_name"].isna().sum())

print("\nExamples of players with missing first names:")
display(
    players_clean.loc[
        players_clean["first_name"].isna(),
        ["first_name", "last_name", "player_name"]
    ].drop_duplicates().head(15)
)

Missing player display names:
0

Examples of players with missing first names:

      first_name    last_name  player_name
22           NaN      Poliana      Poliana
24           NaN  Andressinha  Andressinha
572          NaN       Monica       Monica
3676         NaN       Camila       Camila
3680         NaN        Marta        Marta
3777         NaN      Debinha      Debinha
11824        NaN        Celia        Celia

In [10]:

# Check for completely identical rows
exact_duplicates = players_clean.duplicated().sum()

print("Exact duplicate rows:", exact_duplicates)

# Check for duplicate player-match records
player_match_duplicates = players_clean.duplicated(
    subset=["game_id", "team_id", "player_id"]
).sum()

print("Duplicate player-match records:", player_match_duplicates)

# Check for blank player display names
blank_names = (
    players_clean["player_name"].fillna("").str.strip() == ""
).sum()

print("Blank player display names:", blank_names)

Exact duplicate rows: 0
Duplicate player-match records: 0
Blank player display names: 0

In [26]:
players_clean.to_csv(
    "nwsl_players_cleaned.csv",
    index=False
)

print("Cleaned player dataset saved successfully!")
print("Rows:", players_clean.shape[0])
print("Columns:", players_clean.shape[1])

Cleaned player dataset saved successfully!
Rows: 15696
Columns: 12

In [12]:

from google.colab import files

files.download("nwsl_players_cleaned.csv")

In [25]:
# Look at the team data and its columns
print("TEAM DATASET SHAPE:")
print(teams.shape)

print("\nALL TEAM COLUMNS:")
print(teams.columns.tolist())

print("\nFIRST FIVE ROWS:")
display(teams.head())

TEAM DATASET SHAPE:
(890, 241)

ALL TEAM COLUMNS:
['game_id', 'status', 'team', 'total_through_ball', 'duel_lost', 'blocked_scoring_att', 'leftside_pass', 'poss_won_att_3_rd', 'dispossessed', 'accurate_keeper_sweeper', 'accurate_cross', 'att_rf_total', 'att_bx_right', 'six_yard_block', 'accurate_pass', 'won_tackle', 'att_assist_setplay', 'att_goal_high_centre', 'att_miss_left', 'total_final_third_passes', 'rightside_pass', 'attempts_conceded_ibox', 'touches', 'total_fwd_zone_pass', 'att_assist_openplay', 'won_contest', 'goals_openplay', 'accurate_fwd_zone_pass', 'total_chipped_pass', 'lost_corners', 'fouled_final_third', 'saves', 'ontarget_scoring_att', 'total_scoring_att', 'blocked_pass', 'attempts_conceded_obox', 'ball_recovery', 'subs_made', 'att_ibox_post', 'poss_won_def_3_rd', 'accurate_back_zone_pass', 'att_cmiss_left', 'att_goal_low_centre', 'goal_assist_openplay', 'passes_right', 'total_throws', 'att_obox_target', 'successful_open_play_pass', 'goal_assist_setplay', 'total_back_zone_pass', 'total_long_balls', 'att_hd_goal', 'accurate_keeper_throws', 'att_obx_centre', 'att_openplay', 'poss_won_mid_3_rd', 'put_through', 'big_chance_created', 'att_ibox_target', 'freekick_cross', 'att_freekick_total', 'goal_kicks', 'att_lf_total', 'open_play_pass', 'goal_assist_intentional', 'aerial_won', 'goal_assist', 'total_pass', 'midfielder_goals', 'total_launches', 'fwd_pass', 'effective_blocked_cross', 'outfielder_block', 'att_miss_high_left', 'goals', 'touches_in_opp_box', 'total_corners_intobox', 'blocked_cross', 'att_miss_right', 'att_bx_centre', 'post_scoring_att', 'ontarget_att_assist', 'long_pass_own_to_opp', 'att_ibox_goal', 'accurate_chipped_pass', 'duel_won', 'total_keeper_sweeper', 'successful_final_third_passes', 'att_rf_goal', 'shield_ball_oop', 'fk_foul_won', 'total_cross_nocorner', 'keeper_throws', 'att_bx_left', 'successful_put_through', 'total_tackle', 'att_sv_low_left', 'passes_left', 'big_chance_scored', 'att_rf_target', 'att_cmiss_high_left', 'accurate_launches', 'poss_lost_all', 'att_sv_low_centre', 'accurate_long_balls', 'challenge_lost', 'total_cross', 'att_goal_low_right', 'clean_sheet', 'att_obox_blocked', 'att_ibox_miss', 'accurate_goal_kicks', 'saved_obox', 'unsuccessful_touch', 'shot_off_target', 'forward_goals', 'poss_lost_ctrl', 'hand_ball', 'goal_assist_deadball', 'att_ibox_blocked', 'aerial_lost', 'att_sv_low_right', 'crosses_18_yard', 'final_third_entries', 'att_hd_total', 'accurate_cross_nocorner', 'effective_clearance', 'fk_foul_lost', 'att_hd_miss', 'won_corners', 'possession_percentage', 'interception', 'attempted_tackle_foul', 'backward_pass', 'first_half_goals', 'interception_won', 'pen_area_entries', 'att_lf_goal', 'accurate_throws', 'big_chance_missed', 'accurate_freekick_cross', 'att_hd_target', 'total_contest', 'hit_woodwork', 'total_clearance', 'long_pass_own_to_opp_success', 'accurate_corners_intobox', 'total_att_assist', 'att_post_left', 'att_setpiece', 'offtarget_att_assist', 'att_obox_miss', 'corner_taken', 'crosses_18_yardplus', 'formation_used', 'total_shots', 'passing_accuracy', 'shot_faced', 'shots_on_goal', 'total_flick_on', 'diving_save', 'att_freekick_miss', 'goals_conceded', 'att_lg_centre', 'total_high_claim', 'error_lead_to_goal', 'goals_conceded_ibox', 'interceptions_in_box', 'total_offside', 'good_high_claim', 'saved_ibox', 'att_miss_high', 'att_sv_high_centre', 'effective_head_clearance', 'accurate_flick_on', 'accurate_layoffs', 'total_yellow_card', 'head_clearance', 'att_lf_target', 'att_cmiss_right', 'att_sv_high_left', 'att_freekick_target', 'overrun', 'total_layoffs', 'total_pull_back', 'att_miss_high_right', 'accurate_through_ball', 'clearance_off_line', 'att_post_high', 'att_cmiss_high', 'att_goal_low_left', 'att_sv_high_right', 'att_obxd_right', 'pts_gained_losing_pos', 'att_cmiss_high_right', 'goals_conceded_obox', 'att_obox_goal', 'pts_dropped_winning_pos', 'error_lead_to_shot', 'att_goal_high_right', 'penalty_conceded', 'penalty_faced', 'att_obx_right', 'pen_goals_conceded', 'att_pen_goal', 'att_goal_high_left', 'penalty_won', 'punches', 'own_goal_accrued', 'att_ibox_own_goal', 'own_goals', 'att_obox_post', 'second_yellow', 'total_red_card', 'defender_goals', 'att_one_on_one', 'att_freekick_post', 'att_pen_post', 'att_post_right', 'contentious_decision', 'att_obxd_left', 'att_hd_post', 'foul_throw_in', 'att_lg_left', 'att_fastbreak', 'shot_fastbreak', 'total_fastbreak', 'att_obx_left', 'accurate_pull_back', 'att_freekick_goal', 'last_man_tackle', 'attempts_obox', 'attempts_ibox', 'att_pen_miss', 'goal_fastbreak', 'att_obp_goal', 'penalty_save', 'att_pen_target', 'att_lg_right', 'att_corner', 'season']

FIRST FIVE ROWS:

,game_id,status,team,total_through_ball,duel_lost,blocked_scoring_att,leftside_pass,poss_won_att_3_rd,dispossessed,accurate_keeper_sweeper,...,attempts_obox,attempts_ibox,att_pen_miss,goal_fastbreak,att_obp_goal,penalty_save,att_pen_target,att_lg_right,att_corner,season
0,portland-thorns-vs-houston-dash-2016-09-07,home,POR,1,32,5,112,13,16,1,...,0,0,0.0,0,0,0,0,NaN,NaN,2016
1,portland-thorns-vs-houston-dash-2016-09-07,away,HOU,1,35,2,78,3,17,1,...,0,0,0.0,0,0,0,0,NaN,NaN,2016
2,western-new-york-flash-vs-kansas-city-2016-07-23,home,WNY,0,56,1,60,11,13,2,...,0,0,0.0,0,0,0,0,NaN,NaN,2016
3,western-new-york-flash-vs-kansas-city-2016-07-23,away,KC,3,49,2,40,2,9,0,...,0,0,0.0,0,0,0,0,NaN,NaN,2016
4,western-new-york-flash-vs-houston-dash-2016-08-27,home,WNY,1,51,1,69,5,4,1,...,0,0,0.0,0,0,0,0,NaN,NaN,2016

In [24]:

# Pick the team stats I want to compare
team_columns = [
    "game_id",
    "season",
    "status",
    "team",
    "goals",
    "goal_assist",
    "total_shots",
    "total_pass",
    "accurate_pass"
]

# Make sure the columns are in the dataset
available = [col for col in team_columns if col in teams.columns]
missing = [col for col in team_columns if col not in teams.columns]

print("Available columns:", available)
print("\nMissing columns:", missing)

teams_clean = teams[available].copy()

# Check the selected team data
print("\nCleaned team dataset shape:")
print(teams_clean.shape)

print("\nMissing values:")
print(teams_clean.isnull().sum())

display(teams_clean.head())

Available columns: ['game_id', 'season', 'status', 'team', 'goals', 'goal_assist', 'total_shots', 'total_pass', 'accurate_pass']

Missing columns: []

Cleaned team dataset shape:
(890, 9)

Missing values:
game_id          0
season           0
status           0
team             0
goals            0
goal_assist      0
total_shots      0
total_pass       0
accurate_pass    0
dtype: int64

,game_id,season,status,team,goals,goal_assist,total_shots,total_pass,accurate_pass
0,portland-thorns-vs-houston-dash-2016-09-07,2016,home,POR,3,2,21,545,464
1,portland-thorns-vs-houston-dash-2016-09-07,2016,away,HOU,0,0,8,394,298
2,western-new-york-flash-vs-kansas-city-2016-07-23,2016,home,WNY,0,0,22,301,206
3,western-new-york-flash-vs-kansas-city-2016-07-23,2016,away,KC,1,1,11,230,125
4,western-new-york-flash-vs-houston-dash-2016-08-27,2016,home,WNY,2,2,14,393,278

In [23]:
# Check for duplicate team records
exact_duplicates = teams_clean.duplicated().sum()

team_match_duplicates = teams_clean.duplicated(
    subset=["game_id", "team"]
).sum()

print("Exact duplicate rows:", exact_duplicates)
print("Duplicate team-match records:", team_match_duplicates)

# Make sure the stats are numbers
stats = [
    "goals",
    "goal_assist",
    "total_shots",
    "total_pass",
    "accurate_pass"
]

for col in stats:
    teams_clean[col] = pd.to_numeric(
        teams_clean[col], errors="coerce"
    )

# Look for missing or incorrect values
print("\nInvalid or missing numeric values:")
print(teams_clean[stats].isna().sum())

print("\nNegative values:")
print((teams_clean[stats] < 0).sum())

# Completed passes shouldn't be higher than total passes
invalid_passes = (
    teams_clean["accurate_pass"] >
    teams_clean["total_pass"]
).sum()

print("\nMatches with completed passes exceeding total passes:",
      invalid_passes)

Exact duplicate rows: 0
Duplicate team-match records: 0

Invalid or missing numeric values:
goals            0
goal_assist      0
total_shots      0
total_pass       0
accurate_pass    0
dtype: int64

Negative values:
goals            0
goal_assist      0
total_shots      0
total_pass       0
accurate_pass    0
dtype: int64

Matches with completed passes exceeding total passes: 0

In [16]:
teams_clean.to_csv(
    "nwsl_teams_cleaned.csv",
    index=False
)

print("Cleaned team dataset saved successfully!")
print("Rows:", teams_clean.shape[0])
print("Columns:", teams_clean.shape[1])

Cleaned team dataset saved successfully!
Rows: 890
Columns: 9

In [17]:

from google.colab import files

files.download("nwsl_teams_cleaned.csv")